// -------------------------------------------------------------
// 
// File Name: C:\Users\pc\Documents\MATLAB\MY_FSK\HDL_MODULATOR\hdlsrc\FSK_MODULATOR_HARDWARE_MODEL\FSK_MODULATOR_HARDWARE_MODEL_pkg.sv
// Created: 2026-04-28 01:43:05
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------



package FSK_MODULATOR_HARDWARE_MODEL_pkg;
  typedef  logic signed [16:0] vector_of_signed_logic_17;
  typedef  logic  [12:0] vector_of_unsigned_logic_13;

  typedef  logic  [27:0] vector_of_unsigned_logic_28;
endpackage: FSK_MODULATOR_HARDWARE_MODEL_pkg

