// -------------------------------------------------------------
// 
// File Name: C:\Users\pc\Documents\MATLAB\MY_FSK\HDL_MODULATOR\hdlsrc\FSK_MODULATOR_HARDWARE_MODEL\FSK_MODULATOR_HARDWARE_MODEL.sv
// Created: 2026-04-28 01:43:05
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1e-08
// Target subsystem base rate: 1e-08
// 
// -------------------------------------------------------------


import FSK_MODULATOR_HARDWARE_MODEL_pkg::* ;

// -------------------------------------------------------------
// 
// Module: FSK_MODULATOR_HARDWARE_MODEL
// Source Path: FSK_MODULATOR_HARDWARE_MODEL/FSK_MODULATOR_HARDWARE_MODEL
// Hierarchy Level: 0
// Model version: 1.3
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FSK_MODULATOR_HARDWARE_MODEL
          (  input logic clk,
             input logic reset,
             input logic modulating_signal,
             output logic signed [16:0] modulated_signal  /* sfix17_En15 */);


  logic signed [16:0] Constant1_out1;  /* sfix17_En15 */
  logic signed [16:0] Constant_out1;  /* sfix17_En15 */
  logic signed [16:0] mx1;  /* sfix17_En15 */
  logic signed [44:0] Gain_1_mul_temp;  /* sfix45_En42 */
  logic signed [43:0] Gain_1_cast;  /* sfix44_En42 */
  logic signed [27:0] Gain_1_out1;  /* sfix28_En27 */
  logic signed [27:0] reg1_out1;  /* sfix28_En27 */
  logic signed [27:0] Integrator_x_reg;  /* sfix28_En27 */
  logic signed [27:0] Integrator_u_add;  /* sfix28_En27 */
  logic [15:0] count_step;  /* uint16 */
  logic [15:0] count_from;  /* uint16 */
  logic [15:0] carrier_signal_phase_cnt_out1;  /* uint16 */
  logic [15:0] count;  /* uint16 */
  logic need_to_wrap;
  logic [15:0] count_value;  /* uint16 */
  logic [26:0] Const_out1;  /* ufix27_En27 */
  logic [42:0] carrier_signal_phase_mul_temp;  /* ufix43_En27 */
  logic [27:0] carrier_signal_phase_out1;  /* ufix28_En28 */
  vector_of_unsigned_logic_28 carrier_signal_phase_reg_reg [0:1];  /* ufix28 [2] */
  logic [27:0] carrier_signal_phase_reg_out1;  /* ufix28_En28 */
  logic signed [28:0] sum_phase_add_cast;  /* sfix29_En28 */
  logic signed [28:0] sum_phase_add_cast_1;  /* sfix29_En28 */
  logic signed [28:0] sum_phase_add_temp;  /* sfix29_En28 */
  logic signed [31:0] sum_phase_out1;  /* sfix32_En28 */
  logic signed [31:0] sum_phase_reg_out1;  /* sfix32_En28 */
  logic signed [16:0] Cosine_1;  /* sfix17_En15 */
  logic signed [16:0] cosine_reg_out1;  /* sfix17_En15 */


  assign Constant1_out1 = 17'sb11000000000000000;
	typedef  logic signed [16:0] vector_of_signed_logic_17;
  typedef  logic  [12:0] vector_of_unsigned_logic_13;

  typedef  logic  [27:0] vector_of_unsigned_logic_28;


  assign Constant_out1 = 17'sb01000000000000000;



  assign mx1 = (modulating_signal == 1'b0 ? Constant1_out1 :
              Constant_out1);



  assign Gain_1_mul_temp = 28'sb0000000000000000101001111100 * mx1;
  assign Gain_1_cast = Gain_1_mul_temp[43:0];
  assign Gain_1_out1 = Gain_1_cast[42:15] + $signed({1'b0, Gain_1_cast[14] & (( ~ Gain_1_cast[43]) | (|Gain_1_cast[13:0]))});



  always_ff @(posedge clk or posedge reset)
    begin : reg1_process
      if (reset == 1'b1) begin
        reg1_out1 <= 28'sb0000000000000000000000000000;
      end
      else begin
        reg1_out1 <= Gain_1_out1;
      end
    end



  assign Integrator_u_add = Integrator_x_reg + reg1_out1;



  always_ff @(posedge clk or posedge reset)
    begin : Integrator_reg_process
      if (reset == 1'b1) begin
        Integrator_x_reg <= 28'sb0000000000000000000000000000;
      end
      else begin
        Integrator_x_reg <= Integrator_u_add;
      end
    end



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 10000
  assign count_step = 16'b0000000000000001;



  assign count_from = 16'b0000000000000000;



  assign count = carrier_signal_phase_cnt_out1 + count_step;



  assign need_to_wrap = carrier_signal_phase_cnt_out1 == 16'b0010011100010000;



  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);



  always_ff @(posedge clk or posedge reset)
    begin : carrier_signal_phase_cnt_process
      if (reset == 1'b1) begin
        carrier_signal_phase_cnt_out1 <= 16'b0000000000000000;
      end
      else begin
        carrier_signal_phase_cnt_out1 <= count_value;
      end
    end



  assign Const_out1 = 27'b000000000000011010001101110;



  assign carrier_signal_phase_mul_temp = carrier_signal_phase_cnt_out1 * Const_out1;
  assign carrier_signal_phase_out1 = {carrier_signal_phase_mul_temp[26:0], 1'b0};



  always_ff @(posedge clk or posedge reset)
    begin : carrier_signal_phase_reg_process
      if (reset == 1'b1) begin
        carrier_signal_phase_reg_reg <= '{2{28'b0000000000000000000000000000}};
      end
      else begin
        carrier_signal_phase_reg_reg[0] <= carrier_signal_phase_out1;
        carrier_signal_phase_reg_reg[1] <= carrier_signal_phase_reg_reg[0];
      end
    end

  assign carrier_signal_phase_reg_out1 = carrier_signal_phase_reg_reg[1];



  assign sum_phase_add_cast = {Integrator_x_reg, 1'b0};
  assign sum_phase_add_cast_1 = {1'b0, carrier_signal_phase_reg_out1};
  assign sum_phase_add_temp = sum_phase_add_cast + sum_phase_add_cast_1;
  assign sum_phase_out1 = {{3{sum_phase_add_temp[28]}}, sum_phase_add_temp};



  always_ff @(posedge clk or posedge reset)
    begin : sum_phase_reg_process
      if (reset == 1'b1) begin
        sum_phase_reg_out1 <= 32'sb00000000000000000000000000000000;
      end
      else begin
        sum_phase_reg_out1 <= sum_phase_out1;
      end
    end



  cosine u_cosine (.clk(clk),
                   .reset(reset),
                   .u(sum_phase_reg_out1),  /* sfix32_En28 */
                   .x(Cosine_1)  /* sfix17_En15 */
                   );

  always_ff @(posedge clk or posedge reset)
    begin : cosine_reg_process
      if (reset == 1'b1) begin
        cosine_reg_out1 <= 17'sb00000000000000000;
      end
      else begin
        cosine_reg_out1 <= Cosine_1;
      end
    end



  assign modulated_signal = cosine_reg_out1;

endmodule  // FSK_MODULATOR_HARDWARE_MODEL

