// -------------------------------------------------------------
// 
// File Name: C:\Users\pc\Documents\MATLAB\MY_FSK\HDL_MODULATOR\hdlsrc\FSK_MODULATOR_HARDWARE_MODEL\FSK_MODULATOR_HARDWARE_MODEL_tb.sv
// Created: 2026-04-28 01:44:08
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1e-08
// Target subsystem base rate: 1e-08
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FSK_MODULATOR_HARDWARE_MODEL_tb
// Source Path: 
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FSK_MODULATOR_HARDWARE_MODEL_tb;

  logic clk;
  logic reset;
  logic enb;
  logic modulated_signal_done;  /* ufix1 */
  logic rdEnb;
  logic modulated_signal_done_enb;  /* ufix1 */
  logic [17:0] modulated_signal_addr;  /* ufix18 */
  logic modulated_signal_active;  /* ufix1 */
  logic check1_done;  /* ufix1 */
  logic snkDonen;
  logic resetn;
  logic tb_enb;
  logic ce_out;
  logic modulated_signal_enb;  /* ufix1 */
  logic modulated_signal_lastAddr;  /* ufix1 */
  logic [17:0] Data_Type_Conversion1_out1_addr;  /* ufix18 */
  logic Data_Type_Conversion1_out1_active;  /* ufix1 */
  logic Data_Type_Conversion1_out1_enb;  /* ufix1 */
  logic [17:0] Data_Type_Conversion1_out1_addr_delay_1;  /* ufix18 */
  logic signed [31:0] fp_modulating_signal;  /* sfix32 */
  logic modulating_signalraw;
  logic signed [31:0] status_modulating_signal;  /* sfix32 */
  logic rawData_modulating_signal;
  logic holdData_modulating_signal;
  logic modulating_signal_offset;
  logic modulating_signal;
  logic signed [16:0] modulated_signal;  /* sfix17_En15 */
  logic [17:0] modulated_signal_addr_delay_1;  /* ufix18 */
  logic signed [31:0] fp_modulated_signal_expected;  /* sfix32 */
  logic signed [16:0] modulated_signal_expected;  /* sfix17_En15 */
  logic signed [31:0] status_modulated_signal_expected;  /* sfix32 */
  logic signed [16:0] modulated_signal_ref;  /* sfix17_En15 */
  logic modulated_signal_testFailure;  /* ufix1 */
  logic testFailure;  /* ufix1 */


  assign modulated_signal_done_enb = modulated_signal_done & rdEnb;



  assign modulated_signal_active = modulated_signal_addr != 18'b101010101110011000;



  assign #1 enb = rdEnb;

  assign snkDonen =  ~ check1_done;



  always 
    begin : clk_gen
      clk <= 1'b1;
      # (5);
      clk <= 1'b0;
      # (5);
      if (check1_done == 1'b1) begin
        clk <= 1'b1;
        # (5);
        clk <= 1'b0;
        # (5);
        $stop;
      end
    end

  initial
    begin : reset_gen
      reset <= 1'b1;
      # (20);
      @ (posedge clk)
      # (1);
      reset <= 1'b0;
    end

  assign resetn =  ~ reset;



  assign tb_enb = resetn & snkDonen;



  assign rdEnb = (check1_done == 1'b0 ? tb_enb :
              1'b0);



  assign ce_out = enb & (rdEnb & tb_enb);



  assign modulated_signal_enb = ce_out & modulated_signal_active;



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 175000
  always_ff @(posedge clk or posedge reset)
    begin : c_2_process
      if (reset == 1'b1) begin
        modulated_signal_addr <= 18'b000000000000000000;
      end
      else begin
        if (modulated_signal_enb) begin
          if (modulated_signal_addr >= 18'b101010101110011000) begin
            modulated_signal_addr <= 18'b000000000000000000;
          end
          else begin
            modulated_signal_addr <= modulated_signal_addr + 18'b000000000000000001;
          end
        end
      end
    end



  assign modulated_signal_lastAddr = modulated_signal_addr >= 18'b101010101110011000;



  assign modulated_signal_done = modulated_signal_lastAddr & resetn;



  // Delay to allow last sim cycle to complete
  always @(posedge clk or posedge reset)
    begin : checkDone_1
      if (reset) begin
        check1_done <= 0;
      end
      else begin
        if (modulated_signal_done_enb) begin
          check1_done <= modulated_signal_done;
        end
      end
    end

  assign Data_Type_Conversion1_out1_active = Data_Type_Conversion1_out1_addr != 18'b101010101110011000;



  assign Data_Type_Conversion1_out1_enb = Data_Type_Conversion1_out1_active & (rdEnb & tb_enb);



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 175000
  always_ff @(posedge clk or posedge reset)
    begin : DataTypeConversion1_process
      if (reset == 1'b1) begin
        Data_Type_Conversion1_out1_addr <= 18'b000000000000000000;
      end
      else begin
        if (Data_Type_Conversion1_out1_enb) begin
          if (Data_Type_Conversion1_out1_addr >= 18'b101010101110011000) begin
            Data_Type_Conversion1_out1_addr <= 18'b000000000000000000;
          end
          else begin
            Data_Type_Conversion1_out1_addr <= Data_Type_Conversion1_out1_addr + 18'b000000000000000001;
          end
        end
      end
    end



  assign #1 Data_Type_Conversion1_out1_addr_delay_1 = Data_Type_Conversion1_out1_addr;

  // Data source for modulating_signal
  initial
    begin : modulating_signal_fileread
      fp_modulating_signal = $fopen("modulating_signal.dat", "r");
      status_modulating_signal = $rewind(fp_modulating_signal);
    end

  always @(Data_Type_Conversion1_out1_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        modulating_signalraw <= 1'b0;
      end
      else if (rdEnb == 1) begin
        status_modulating_signal = $fscanf(fp_modulating_signal, "%h", modulating_signalraw);
      end
    end

  assign rawData_modulating_signal = (rdEnb == 1'b0 ? 1'b0 :
              modulating_signalraw);



  // holdData reg for Data_Type_Conversion1_out1
  always @(posedge clk or posedge reset)
    begin : stimuli_Data_Type_Conversion1_out1
      if (reset) begin
        holdData_modulating_signal <= 0;
      end
      else begin
        holdData_modulating_signal <= rawData_modulating_signal;
      end
    end

  always @(rawData_modulating_signal or rdEnb or tb_enb)
    begin : stimuli_Data_Type_Conversion1_out1_1
      if (tb_enb == 1'b0) begin
        modulating_signal_offset <= 1'b0;
      end
      else begin
        if (rdEnb == 1'b0) begin
          modulating_signal_offset <= holdData_modulating_signal;
        end
        else begin
          modulating_signal_offset <= rawData_modulating_signal;
        end
      end
    end

  assign #1 modulating_signal = modulating_signal_offset;

  FSK_MODULATOR_HARDWARE_MODEL u_FSK_MODULATOR_HARDWARE_MODEL (.clk(clk),
                                                               .reset(reset),
                                                               .modulating_signal(modulating_signal),
                                                               .modulated_signal(modulated_signal)  /* sfix17_En15 */
                                                               );

  assign #1 modulated_signal_addr_delay_1 = modulated_signal_addr;

  // Data source for modulated_signal_expected
  initial
    begin : modulated_signal_expected_fileread
      fp_modulated_signal_expected = $fopen("modulated_signal_expected.dat", "r");
      status_modulated_signal_expected = $rewind(fp_modulated_signal_expected);
    end

  always @(modulated_signal_addr_delay_1, rdEnb, tb_enb)
    begin
      if (tb_enb == 0) begin
        modulated_signal_expected <= 17'b0;
      end
      else if (rdEnb == 1) begin
        status_modulated_signal_expected = $fscanf(fp_modulated_signal_expected, "%h", modulated_signal_expected);
      end
    end

  assign modulated_signal_ref = modulated_signal_expected;

  always @(posedge clk or posedge reset)
    begin : modulated_signal_checker
      if (reset == 1'b1) begin
        modulated_signal_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && modulated_signal !== modulated_signal_ref) begin
          modulated_signal_testFailure <= 1'b1;
          $display("ERROR in modulated_signal at time %t : Expected '%h' Actual '%h'", $time, modulated_signal_ref, modulated_signal);
        end
      end
    end

  assign testFailure = modulated_signal_testFailure;

  always @(posedge clk)
    begin : completed_msg
      if (check1_done == 1'b1) begin
        if (testFailure == 1'b0) begin
          $display("**************TEST COMPLETED (PASSED)**************");
        end
        else begin
          $display("**************TEST COMPLETED (FAILED)**************");
        end
      end
    end

endmodule  // FSK_MODULATOR_HARDWARE_MODEL_tb

