// -------------------------------------------------------------
// 
// File Name: C:\Users\pc\Documents\MATLAB\MY_FSK\HDL_DEMODULATOR\hdlsrc\FSK_DEMODULATOR_HARDWARE_MODEL\HARDWARE_FRIENDLY_FSK\FSK_DEMODULATOR_HARDWARE_MODEL_tb.sv
// Created: 2026-04-28 11:17:43
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1e-08
// Target subsystem base rate: 1e-08
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: FSK_DEMODULATOR_HARDWARE_MODEL_tb
// Source Path: 
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FSK_DEMODULATOR_HARDWARE_MODEL_tb;

  logic clk;
  logic reset;
  logic clk_enable;
  logic demodulated_signal_done;  /* ufix1 */
  logic rdEnb;
  logic demodulated_signal_done_enb;  /* ufix1 */
  logic [17:0] demodulated_signal_addr;  /* ufix18 */
  logic demodulated_signal_active;  /* ufix1 */
  logic [17:0] FSK_MODULATOR_HARDWARE_MODEL_out1_addr;  /* ufix18 */
  logic FSK_MODULATOR_HARDWARE_MODEL_out1_active;  /* ufix1 */
  logic tb_enb_delay;
  logic FSK_MODULATOR_HARDWARE_MODEL_out1_enb;  /* ufix1 */
  logic [17:0] FSK_MODULATOR_HARDWARE_MODEL_out1_addr_delay_1;  /* ufix18 */
  logic signed [31:0] fp_modulated_signal;  /* sfix32 */
  logic signed [16:0] rawData_modulated_signal;  /* sfix17_En15 */
  logic signed [31:0] status_modulated_signal;  /* sfix32 */
  logic signed [16:0] holdData_modulated_signal;  /* sfix17_En15 */
  logic signed [16:0] modulated_signal_offset;  /* sfix17_En15 */
  logic signed [16:0] modulated_signal;  /* sfix17_En15 */
  logic check1_done;  /* ufix1 */
  logic snkDonen;
  logic resetn;
  logic tb_enb;
  logic ce_out;
  logic demodulated_signal;
  logic demodulated_signal_enb;  /* ufix1 */
  logic demodulated_signal_lastAddr;  /* ufix1 */
  logic [17:0] demodulated_signal_addr_delay_1;  /* ufix18 */
  logic signed [31:0] fp_demodulated_signal_expected;  /* sfix32 */
  logic demodulated_signal_expected;
  logic signed [31:0] status_demodulated_signal_expected;  /* sfix32 */
  logic demodulated_signal_ref;
  logic demodulated_signal_testFailure;  /* ufix1 */
  logic testFailure;  /* ufix1 */


  assign demodulated_signal_done_enb = demodulated_signal_done & rdEnb;



  assign demodulated_signal_active = demodulated_signal_addr != 18'b101010101110011000;



  assign FSK_MODULATOR_HARDWARE_MODEL_out1_active = FSK_MODULATOR_HARDWARE_MODEL_out1_addr != 18'b101010101110011000;



  assign FSK_MODULATOR_HARDWARE_MODEL_out1_enb = FSK_MODULATOR_HARDWARE_MODEL_out1_active & (rdEnb & tb_enb_delay);



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 175000
  always_ff @(posedge clk or posedge reset)
    begin : FSK_MODULATOR_HARDWARE_MODEL_process
      if (reset == 1'b1) begin
        FSK_MODULATOR_HARDWARE_MODEL_out1_addr <= 18'b000000000000000000;
      end
      else begin
        if (FSK_MODULATOR_HARDWARE_MODEL_out1_enb) begin
          if (FSK_MODULATOR_HARDWARE_MODEL_out1_addr >= 18'b101010101110011000) begin
            FSK_MODULATOR_HARDWARE_MODEL_out1_addr <= 18'b000000000000000000;
          end
          else begin
            FSK_MODULATOR_HARDWARE_MODEL_out1_addr <= FSK_MODULATOR_HARDWARE_MODEL_out1_addr + 18'b000000000000000001;
          end
        end
      end
    end



  assign #1 FSK_MODULATOR_HARDWARE_MODEL_out1_addr_delay_1 = FSK_MODULATOR_HARDWARE_MODEL_out1_addr;

  // Data source for modulated_signal
  initial
    begin : modulated_signal_fileread
      fp_modulated_signal = $fopen("modulated_signal.dat", "r");
      status_modulated_signal = $rewind(fp_modulated_signal);
    end

  always @(FSK_MODULATOR_HARDWARE_MODEL_out1_addr_delay_1, rdEnb, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        rawData_modulated_signal <= 17'bx;
      end
      else if (rdEnb == 1) begin
        status_modulated_signal = $fscanf(fp_modulated_signal, "%h", rawData_modulated_signal);
      end
    end

  // holdData reg for FSK_MODULATOR_HARDWARE_MODEL_out1
  always @(posedge clk or posedge reset)
    begin : stimuli_FSK_MODULATOR_HARDWARE_MODEL_out1
      if (reset) begin
        holdData_modulated_signal <= 17'bx;
      end
      else begin
        holdData_modulated_signal <= rawData_modulated_signal;
      end
    end

  always @(rawData_modulated_signal or rdEnb)
    begin : stimuli_FSK_MODULATOR_HARDWARE_MODEL_out1_1
      if (rdEnb == 1'b0) begin
        modulated_signal_offset <= holdData_modulated_signal;
      end
      else begin
        modulated_signal_offset <= rawData_modulated_signal;
      end
    end

  assign #2 modulated_signal = modulated_signal_offset;

  assign snkDonen =  ~ check1_done;



  assign resetn =  ~ reset;



  assign tb_enb = resetn & snkDonen;



  // Delay inside enable generation: register depth 1
  always_ff @(posedge clk or posedge reset)
    begin : u_enable_delay_process
      if (reset == 1'b1) begin
        tb_enb_delay <= 1'b0;
      end
      else begin
        tb_enb_delay <= tb_enb;
      end
    end



  assign rdEnb = (check1_done == 1'b0 ? tb_enb_delay :
              1'b0);



  assign #2 clk_enable = rdEnb;

  initial
    begin : reset_gen
      reset <= 1'b1;
      # (20);
      @ (posedge clk)
      # (2);
      reset <= 1'b0;
    end

  always 
    begin : clk_gen
      clk <= 1'b1;
      # (5);
      clk <= 1'b0;
      # (5);
      if (check1_done == 1'b1) begin
        clk <= 1'b1;
        # (5);
        clk <= 1'b0;
        # (5);
        $stop;
      end
    end

  FSK_DEMODULATOR_HARDWARE_MODEL u_FSK_DEMODULATOR_HARDWARE_MODEL (.clk(clk),
                                                                   .reset(reset),
                                                                   .clk_enable(clk_enable),
                                                                   .modulated_signal(modulated_signal),  /* sfix17_En15 */
                                                                   .ce_out(ce_out),
                                                                   .demodulated_signal(demodulated_signal)
                                                                   );

  assign demodulated_signal_enb = ce_out & demodulated_signal_active;



  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 175000
  always_ff @(posedge clk or posedge reset)
    begin : c_2_process
      if (reset == 1'b1) begin
        demodulated_signal_addr <= 18'b000000000000000000;
      end
      else begin
        if (demodulated_signal_enb) begin
          if (demodulated_signal_addr >= 18'b101010101110011000) begin
            demodulated_signal_addr <= 18'b000000000000000000;
          end
          else begin
            demodulated_signal_addr <= demodulated_signal_addr + 18'b000000000000000001;
          end
        end
      end
    end



  assign demodulated_signal_lastAddr = demodulated_signal_addr >= 18'b101010101110011000;



  assign demodulated_signal_done = demodulated_signal_lastAddr & resetn;



  // Delay to allow last sim cycle to complete
  always @(posedge clk or posedge reset)
    begin : checkDone_1
      if (reset) begin
        check1_done <= 0;
      end
      else begin
        if (demodulated_signal_done_enb) begin
          check1_done <= demodulated_signal_done;
        end
      end
    end

  assign #1 demodulated_signal_addr_delay_1 = demodulated_signal_addr;

  // Data source for demodulated_signal_expected
  initial
    begin : demodulated_signal_expected_fileread
      fp_demodulated_signal_expected = $fopen("demodulated_signal_expected.dat", "r");
      status_demodulated_signal_expected = $rewind(fp_demodulated_signal_expected);
    end

  always @(demodulated_signal_addr_delay_1, ce_out, tb_enb_delay)
    begin
      if (tb_enb_delay == 0) begin
        demodulated_signal_expected <= 1'bx;
      end
      else if (ce_out == 1) begin
        status_demodulated_signal_expected = $fscanf(fp_demodulated_signal_expected, "%h", demodulated_signal_expected);
      end
    end

  assign demodulated_signal_ref = demodulated_signal_expected;

  always @(posedge clk or posedge reset)
    begin : demodulated_signal_checker
      if (reset == 1'b1) begin
        demodulated_signal_testFailure <= 1'b0;
      end
      else begin
        if (ce_out == 1'b1 && demodulated_signal !== demodulated_signal_ref) begin
          demodulated_signal_testFailure <= 1'b1;
          $display("ERROR in demodulated_signal at time %t : Expected '%h' Actual '%h'", $time, demodulated_signal_ref, demodulated_signal);
        end
      end
    end

  assign testFailure = demodulated_signal_testFailure;

  always @(posedge clk)
    begin : completed_msg
      if (check1_done == 1'b1) begin
        if (testFailure == 1'b0) begin
          $display("**************TEST COMPLETED (PASSED)**************");
        end
        else begin
          $display("**************TEST COMPLETED (FAILED)**************");
        end
      end
    end

endmodule  // FSK_DEMODULATOR_HARDWARE_MODEL_tb

