// -------------------------------------------------------------
// 
// File Name: C:\Users\pc\Documents\MATLAB\MY_FSK\HDL_DEMODULATOR\hdlsrc\FSK_DEMODULATOR_HARDWARE_MODEL\HARDWARE_FRIENDLY_FSK\FSK_DEMODULATOR_HARDWARE_MODEL.sv
// Created: 2026-04-28 11:08:04
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1e-08
// Target subsystem base rate: 1e-08
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1e-08
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// demodulated_signal            ce_out        1e-08
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


import FSK_DEMODULATOR_HARDWARE_MODEL_pkg::* ;

// -------------------------------------------------------------
// 
// Module: FSK_DEMODULATOR_HARDWARE_MODEL
// Source Path: HARDWARE_FRIENDLY_FSK/FSK_DEMODULATOR_HARDWARE_MODEL
// Hierarchy Level: 0
// Model version: 1.17
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module FSK_DEMODULATOR_HARDWARE_MODEL
          (  input logic clk,
             input logic reset,
             input logic clk_enable,
             input logic signed [16:0] modulated_signal  /* sfix17_En15 */,
             output logic ce_out,
             output logic demodulated_signal);


  logic enb;
  logic [29:0] count_step;  /* ufix30 */
  logic [29:0] count_from;  /* ufix30 */
  logic [29:0] HDL_Counter_out1;  /* ufix30 */
  logic [29:0] count;  /* ufix30 */
  logic need_to_wrap;
  logic [29:0] count_value;  /* ufix30 */
  logic Compare_To_Constant_out1;
  logic Compare_To_Constant_out1_delay;
  logic Compare_To_Constant_out1_delayN;
  logic Constant1_out1;
  logic signed [15:0] NCO_out1;  /* sfix16_En15 */
  logic signed [15:0] NCO_out2;  /* sfix16_En15 */
  logic signed [15:0] Delay2_out1;  /* sfix16_En15 */
  logic signed [32:0] Product_mul_temp;  /* sfix33_En30 */
  logic signed [29:0] alpha_1_1;  /* sfix30_En29 */
  logic signed [29:0] Delay5_out1;  /* sfix30_En29 */
  logic Compare_To_Constant_out1_rEdge;
  logic signed [29:0] Delay5_out1_dlyBalance;  /* sfix30_En29 */
  logic signed [45:0] Discrete_Time_Integrator_u_dtc;  /* sfix46_En29 */
  logic signed [45:0] Discrete_Time_Integrator_ic;  /* sfix46_En29 */
  logic signed [45:0] Discrete_Time_Integrator_x_reg;  /* sfix46_En29 */
  logic signed [45:0] Discrete_Time_Integrator_add_in;  /* sfix46_En29 */
  logic signed [45:0] Discrete_Time_Integrator_u_add;  /* sfix46_En29 */
  logic signed [45:0] Delay9_out1;  /* sfix46_En29 */
  logic signed [21:0] Data_Type_Conversion_out1;  /* sfix22_En5 */
  logic signed [43:0] Product4_mul_temp;  /* sfix44_En10 */
  logic signed [42:0] Product4_out1;  /* sfix43_En5 */
  logic signed [42:0] Delay13_out1;  /* sfix43_En5 */
  logic Compare_To_Constant_out1_delay_1;
  logic Compare_To_Constant_out1_delayN_1;
  logic signed [15:0] Delay1_out1;  /* sfix16_En15 */
  logic signed [32:0] Product1_mul_temp;  /* sfix33_En30 */
  logic signed [26:0] Product1_out1;  /* sfix27_En25 */
  logic signed [26:0] Delay6_out1;  /* sfix27_En25 */
  logic Compare_To_Constant_out1_rEdge_1;
  logic signed [26:0] Delay6_out1_dlyBalance;  /* sfix27_En25 */
  logic signed [26:0] Discrete_Time_Integrator1_indtc;  /* sfix27 */
  logic signed [27:0] gain_cast;  /* sfix28_E4 */
  logic signed [45:0] Discrete_Time_Integrator1_u_gain;  /* sfix46 */
  logic signed [45:0] Discrete_Time_Integrator1_u_dtc;  /* sfix46_En29 */
  logic signed [45:0] Discrete_Time_Integrator1_ic;  /* sfix46_En29 */
  logic signed [45:0] Discrete_Time_Integrator1_x_reg;  /* sfix46_En29 */
  logic signed [45:0] Discrete_Time_Integrator1_add_in;  /* sfix46_En29 */
  logic signed [45:0] Discrete_Time_Integrator1_u_add;  /* sfix46_En29 */
  logic signed [45:0] Delay10_out1;  /* sfix46_En29 */
  logic signed [21:0] Data_Type_Conversion1_out1;  /* sfix22_En5 */
  logic signed [43:0] Product5_mul_temp;  /* sfix44_En10 */
  logic signed [42:0] Product5_out1;  /* sfix43_En5 */
  logic signed [42:0] Delay14_out1;  /* sfix43_En5 */
  logic [45:0] Sum_add_cast;  /* ufix46_En5 */
  logic [45:0] Sum_add_cast_1;  /* ufix46_En5 */
  logic [45:0] Sum_add_temp;  /* ufix46_En5 */
  logic signed [43:0] Sum_out1;  /* sfix44_En5 */
  logic signed [43:0] Delay17_out1;  /* sfix44_En5 */
  logic Compare_To_Constant_out1_delay_2;
  logic Compare_To_Constant_out1_delayN_2;
  logic Constant2_out1;
  logic signed [17:0] NCO1_out1;  /* sfix18_En17 */
  logic signed [17:0] NCO1_out2;  /* sfix18_En17 */
  logic signed [17:0] Delay4_out1;  /* sfix18_En17 */
  logic signed [34:0] Product2_mul_temp;  /* sfix35_En32 */
  logic signed [26:0] Product2_out1;  /* sfix27_En25 */
  logic signed [26:0] Delay7_out1;  /* sfix27_En25 */
  logic Compare_To_Constant_out1_rEdge_2;
  logic signed [26:0] Delay7_out1_dlyBalance;  /* sfix27_En25 */
  logic signed [26:0] Discrete_Time_Integrator2_indtc;  /* sfix27 */
  logic signed [27:0] gain_cast_1;  /* sfix28_E4 */
  logic signed [45:0] Discrete_Time_Integrator2_u_gain;  /* sfix46 */
  logic signed [45:0] Discrete_Time_Integrator2_u_dtc;  /* sfix46_En29 */
  logic signed [45:0] Discrete_Time_Integrator2_ic;  /* sfix46_En29 */
  logic signed [45:0] Discrete_Time_Integrator2_x_reg;  /* sfix46_En29 */
  logic signed [45:0] Discrete_Time_Integrator2_add_in;  /* sfix46_En29 */
  logic signed [45:0] Discrete_Time_Integrator2_u_add;  /* sfix46_En29 */
  logic signed [45:0] Delay11_out1;  /* sfix46_En29 */
  logic signed [21:0] Data_Type_Conversion2_out1;  /* sfix22_En5 */
  logic signed [43:0] Product6_mul_temp;  /* sfix44_En10 */
  logic signed [42:0] Product6_out1;  /* sfix43_En5 */
  logic signed [42:0] Delay15_out1;  /* sfix43_En5 */
  logic Compare_To_Constant_out1_delay_3;
  logic Compare_To_Constant_out1_delayN_3;
  logic signed [17:0] Delay3_out1;  /* sfix18_En17 */
  logic signed [34:0] Product3_mul_temp;  /* sfix35_En32 */
  logic signed [26:0] Product3_out1;  /* sfix27_En25 */
  logic signed [26:0] Delay8_out1;  /* sfix27_En25 */
  logic Compare_To_Constant_out1_rEdge_3;
  logic signed [26:0] Delay8_out1_dlyBalance;  /* sfix27_En25 */
  logic signed [26:0] Discrete_Time_Integrator3_indtc;  /* sfix27 */
  logic signed [27:0] gain_cast_2;  /* sfix28_E4 */
  logic signed [45:0] Discrete_Time_Integrator3_u_gain;  /* sfix46 */
  logic signed [45:0] Discrete_Time_Integrator3_u_dtc;  /* sfix46_En29 */
  logic signed [45:0] Discrete_Time_Integrator3_ic;  /* sfix46_En29 */
  logic signed [45:0] Discrete_Time_Integrator3_x_reg;  /* sfix46_En29 */
  logic signed [45:0] Discrete_Time_Integrator3_add_in;  /* sfix46_En29 */
  logic signed [45:0] Discrete_Time_Integrator3_u_add;  /* sfix46_En29 */
  logic signed [45:0] Delay12_out1;  /* sfix46_En29 */
  logic signed [21:0] Data_Type_Conversion3_out1;  /* sfix22_En5 */
  logic signed [43:0] Product7_mul_temp;  /* sfix44_En10 */
  logic signed [42:0] Product7_out1;  /* sfix43_En5 */
  logic signed [42:0] Delay16_out1;  /* sfix43_En5 */
  logic signed [43:0] Sum1_add_cast;  /* sfix44_En5 */
  logic signed [43:0] Sum1_add_cast_1;  /* sfix44_En5 */
  logic signed [43:0] Sum1_out1;  /* sfix44_En5 */
  logic signed [43:0] Delay18_out1;  /* sfix44_En5 */
  logic signed [43:0] Sum2_sub_temp;  /* sfix44_En5 */
  logic signed [44:0] Sum2_out1;  /* sfix45_En5 */
  logic signed [44:0] Delay19_out1;  /* sfix45_En5 */
  logic signed [43:0] Constant_out1;  /* sfix44_En5 */
  logic signed [44:0] Relational_Operator_cast;  /* sfix45_En5 */
  logic Relational_Operator_out1;
  logic Sample_and_Hold_out1;


  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 50000
  assign count_step = 30'b000000000000000000000000000001;



  assign count_from = 30'b000000000000000000000000000000;



  assign enb = clk_enable;

  assign count = HDL_Counter_out1 + count_step;



  assign need_to_wrap = HDL_Counter_out1 == 30'b000000000000001100001101010000;



  assign count_value = (need_to_wrap == 1'b0 ? count :
              count_from);



  always_ff @(posedge clk or posedge reset)
    begin : HDL_Counter_process
      if (reset == 1'b1) begin
        HDL_Counter_out1 <= 30'b000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          HDL_Counter_out1 <= count_value;
        end
      end
    end



  assign Compare_To_Constant_out1 = HDL_Counter_out1 <= 30'b000000000000000110000110101000;



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_process
      if (reset == 1'b1) begin
        Compare_To_Constant_out1_delay <= 1'b0;
      end
      else begin
        if (enb) begin
          Compare_To_Constant_out1_delay <= Compare_To_Constant_out1;
        end
      end
    end



  assign Compare_To_Constant_out1_delayN =  ~ Compare_To_Constant_out1_delay;



  assign Constant1_out1 = 1'b1;



  NCO u_NCO (.clk(clk),
             .reset(reset),
             .enb(clk_enable),
             .validIn(Constant1_out1),
             .sine(NCO_out1),  /* sfix16_En15 */
             .cosine(NCO_out2)  /* sfix16_En15 */
             );

  always_ff @(posedge clk or posedge reset)
    begin : Delay2_process
      if (reset == 1'b1) begin
        Delay2_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay2_out1 <= NCO_out2;
        end
      end
    end



  assign Product_mul_temp = Delay2_out1 * modulated_signal;
  assign alpha_1_1 = Product_mul_temp[30:1];



  always_ff @(posedge clk or posedge reset)
    begin : Delay5_process
      if (reset == 1'b1) begin
        Delay5_out1 <= 30'sb000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay5_out1 <= alpha_1_1;
        end
      end
    end



  assign Compare_To_Constant_out1_rEdge = Compare_To_Constant_out1 & Compare_To_Constant_out1_delayN;



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_1_process
      if (reset == 1'b1) begin
        Delay5_out1_dlyBalance <= 30'sb000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay5_out1_dlyBalance <= Delay5_out1;
        end
      end
    end



  assign Discrete_Time_Integrator_u_dtc = {{16{Delay5_out1_dlyBalance[29]}}, Delay5_out1_dlyBalance};



  assign Discrete_Time_Integrator_ic = 46'sh000000000000;



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_2_process
      if (reset == 1'b1) begin
        Discrete_Time_Integrator_add_in <= 46'sh000000000000;
      end
      else begin
        if (enb) begin
          Discrete_Time_Integrator_add_in <= Discrete_Time_Integrator_x_reg;
        end
      end
    end



  assign Discrete_Time_Integrator_u_add = Discrete_Time_Integrator_add_in + Discrete_Time_Integrator_u_dtc;



  assign Discrete_Time_Integrator_x_reg = (Compare_To_Constant_out1_rEdge == 1'b0 ? Discrete_Time_Integrator_u_add :
              Discrete_Time_Integrator_ic);



  always_ff @(posedge clk or posedge reset)
    begin : Delay9_process
      if (reset == 1'b1) begin
        Delay9_out1 <= 46'sh000000000000;
      end
      else begin
        if (enb) begin
          Delay9_out1 <= Discrete_Time_Integrator_x_reg;
        end
      end
    end



  assign Data_Type_Conversion_out1 = Delay9_out1[45:24];



  assign Product4_mul_temp = Data_Type_Conversion_out1 * Data_Type_Conversion_out1;
  assign Product4_out1 = {{4{Product4_mul_temp[43]}}, Product4_mul_temp[43:5]};



  always_ff @(posedge clk or posedge reset)
    begin : Delay13_process
      if (reset == 1'b1) begin
        Delay13_out1 <= 43'sh00000000000;
      end
      else begin
        if (enb) begin
          Delay13_out1 <= Product4_out1;
        end
      end
    end



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_3_process
      if (reset == 1'b1) begin
        Compare_To_Constant_out1_delay_1 <= 1'b0;
      end
      else begin
        if (enb) begin
          Compare_To_Constant_out1_delay_1 <= Compare_To_Constant_out1;
        end
      end
    end



  assign Compare_To_Constant_out1_delayN_1 =  ~ Compare_To_Constant_out1_delay_1;



  always_ff @(posedge clk or posedge reset)
    begin : Delay1_process
      if (reset == 1'b1) begin
        Delay1_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Delay1_out1 <= NCO_out1;
        end
      end
    end



  assign Product1_mul_temp = modulated_signal * Delay1_out1;
  assign Product1_out1 = Product1_mul_temp[31:5];



  always_ff @(posedge clk or posedge reset)
    begin : Delay6_process
      if (reset == 1'b1) begin
        Delay6_out1 <= 27'sb000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay6_out1 <= Product1_out1;
        end
      end
    end



  assign Compare_To_Constant_out1_rEdge_1 = Compare_To_Constant_out1 & Compare_To_Constant_out1_delayN_1;



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_4_process
      if (reset == 1'b1) begin
        Delay6_out1_dlyBalance <= 27'sb000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay6_out1_dlyBalance <= Delay6_out1;
        end
      end
    end



  assign Discrete_Time_Integrator1_indtc = Delay6_out1_dlyBalance;



  assign gain_cast = {Discrete_Time_Integrator1_indtc[26], Discrete_Time_Integrator1_indtc};
  assign Discrete_Time_Integrator1_u_gain = {{14{gain_cast[27]}}, {gain_cast, 4'b0000}};



  assign Discrete_Time_Integrator1_u_dtc = Discrete_Time_Integrator1_u_gain;



  assign Discrete_Time_Integrator1_ic = 46'sh000000000000;



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_5_process
      if (reset == 1'b1) begin
        Discrete_Time_Integrator1_add_in <= 46'sh000000000000;
      end
      else begin
        if (enb) begin
          Discrete_Time_Integrator1_add_in <= Discrete_Time_Integrator1_x_reg;
        end
      end
    end



  assign Discrete_Time_Integrator1_u_add = Discrete_Time_Integrator1_add_in + Discrete_Time_Integrator1_u_dtc;



  assign Discrete_Time_Integrator1_x_reg = (Compare_To_Constant_out1_rEdge_1 == 1'b0 ? Discrete_Time_Integrator1_u_add :
              Discrete_Time_Integrator1_ic);



  always_ff @(posedge clk or posedge reset)
    begin : Delay10_process
      if (reset == 1'b1) begin
        Delay10_out1 <= 46'sh000000000000;
      end
      else begin
        if (enb) begin
          Delay10_out1 <= Discrete_Time_Integrator1_x_reg;
        end
      end
    end



  assign Data_Type_Conversion1_out1 = Delay10_out1[45:24];



  assign Product5_mul_temp = Data_Type_Conversion1_out1 * Data_Type_Conversion1_out1;
  assign Product5_out1 = {{4{Product5_mul_temp[43]}}, Product5_mul_temp[43:5]};



  always_ff @(posedge clk or posedge reset)
    begin : Delay14_process
      if (reset == 1'b1) begin
        Delay14_out1 <= 43'sh00000000000;
      end
      else begin
        if (enb) begin
          Delay14_out1 <= Product5_out1;
        end
      end
    end



  assign Sum_add_cast = {{3{Delay13_out1[42]}}, Delay13_out1};
  assign Sum_add_cast_1 = {{3{Delay14_out1[42]}}, Delay14_out1};
  assign Sum_add_temp = Sum_add_cast + Sum_add_cast_1;
  assign Sum_out1 = $signed(Sum_add_temp[43:0]);



  always_ff @(posedge clk or posedge reset)
    begin : Delay17_process
      if (reset == 1'b1) begin
        Delay17_out1 <= 44'sh00000000000;
      end
      else begin
        if (enb) begin
          Delay17_out1 <= Sum_out1;
        end
      end
    end



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_6_process
      if (reset == 1'b1) begin
        Compare_To_Constant_out1_delay_2 <= 1'b0;
      end
      else begin
        if (enb) begin
          Compare_To_Constant_out1_delay_2 <= Compare_To_Constant_out1;
        end
      end
    end



  assign Compare_To_Constant_out1_delayN_2 =  ~ Compare_To_Constant_out1_delay_2;



  assign Constant2_out1 = 1'b1;



  NCO1 u_NCO1 (.clk(clk),
               .reset(reset),
               .enb(clk_enable),
               .validIn(Constant2_out1),
               .sine(NCO1_out1),  /* sfix18_En17 */
               .cosine(NCO1_out2)  /* sfix18_En17 */
               );

  always_ff @(posedge clk or posedge reset)
    begin : Delay4_process
      if (reset == 1'b1) begin
        Delay4_out1 <= 18'sb000000000000000000;
      end
      else begin
        if (enb) begin
          Delay4_out1 <= NCO1_out2;
        end
      end
    end



  assign Product2_mul_temp = Delay4_out1 * modulated_signal;
  assign Product2_out1 = Product2_mul_temp[33:7];



  always_ff @(posedge clk or posedge reset)
    begin : Delay7_process
      if (reset == 1'b1) begin
        Delay7_out1 <= 27'sb000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay7_out1 <= Product2_out1;
        end
      end
    end



  assign Compare_To_Constant_out1_rEdge_2 = Compare_To_Constant_out1 & Compare_To_Constant_out1_delayN_2;



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_7_process
      if (reset == 1'b1) begin
        Delay7_out1_dlyBalance <= 27'sb000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay7_out1_dlyBalance <= Delay7_out1;
        end
      end
    end



  assign Discrete_Time_Integrator2_indtc = Delay7_out1_dlyBalance;



  assign gain_cast_1 = {Discrete_Time_Integrator2_indtc[26], Discrete_Time_Integrator2_indtc};
  assign Discrete_Time_Integrator2_u_gain = {{14{gain_cast_1[27]}}, {gain_cast_1, 4'b0000}};



  assign Discrete_Time_Integrator2_u_dtc = Discrete_Time_Integrator2_u_gain;



  assign Discrete_Time_Integrator2_ic = 46'sh000000000000;



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_8_process
      if (reset == 1'b1) begin
        Discrete_Time_Integrator2_add_in <= 46'sh000000000000;
      end
      else begin
        if (enb) begin
          Discrete_Time_Integrator2_add_in <= Discrete_Time_Integrator2_x_reg;
        end
      end
    end



  assign Discrete_Time_Integrator2_u_add = Discrete_Time_Integrator2_add_in + Discrete_Time_Integrator2_u_dtc;



  assign Discrete_Time_Integrator2_x_reg = (Compare_To_Constant_out1_rEdge_2 == 1'b0 ? Discrete_Time_Integrator2_u_add :
              Discrete_Time_Integrator2_ic);



  always_ff @(posedge clk or posedge reset)
    begin : Delay11_process
      if (reset == 1'b1) begin
        Delay11_out1 <= 46'sh000000000000;
      end
      else begin
        if (enb) begin
          Delay11_out1 <= Discrete_Time_Integrator2_x_reg;
        end
      end
    end



  assign Data_Type_Conversion2_out1 = Delay11_out1[45:24];



  assign Product6_mul_temp = Data_Type_Conversion2_out1 * Data_Type_Conversion2_out1;
  assign Product6_out1 = {{4{Product6_mul_temp[43]}}, Product6_mul_temp[43:5]};



  always_ff @(posedge clk or posedge reset)
    begin : Delay15_process
      if (reset == 1'b1) begin
        Delay15_out1 <= 43'sh00000000000;
      end
      else begin
        if (enb) begin
          Delay15_out1 <= Product6_out1;
        end
      end
    end



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_9_process
      if (reset == 1'b1) begin
        Compare_To_Constant_out1_delay_3 <= 1'b0;
      end
      else begin
        if (enb) begin
          Compare_To_Constant_out1_delay_3 <= Compare_To_Constant_out1;
        end
      end
    end



  assign Compare_To_Constant_out1_delayN_3 =  ~ Compare_To_Constant_out1_delay_3;



  always_ff @(posedge clk or posedge reset)
    begin : Delay3_process
      if (reset == 1'b1) begin
        Delay3_out1 <= 18'sb000000000000000000;
      end
      else begin
        if (enb) begin
          Delay3_out1 <= NCO1_out1;
        end
      end
    end



  assign Product3_mul_temp = modulated_signal * Delay3_out1;
  assign Product3_out1 = Product3_mul_temp[33:7];



  always_ff @(posedge clk or posedge reset)
    begin : Delay8_process
      if (reset == 1'b1) begin
        Delay8_out1 <= 27'sb000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay8_out1 <= Product3_out1;
        end
      end
    end



  assign Compare_To_Constant_out1_rEdge_3 = Compare_To_Constant_out1 & Compare_To_Constant_out1_delayN_3;



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_10_process
      if (reset == 1'b1) begin
        Delay8_out1_dlyBalance <= 27'sb000000000000000000000000000;
      end
      else begin
        if (enb) begin
          Delay8_out1_dlyBalance <= Delay8_out1;
        end
      end
    end



  assign Discrete_Time_Integrator3_indtc = Delay8_out1_dlyBalance;



  assign gain_cast_2 = {Discrete_Time_Integrator3_indtc[26], Discrete_Time_Integrator3_indtc};
  assign Discrete_Time_Integrator3_u_gain = {{14{gain_cast_2[27]}}, {gain_cast_2, 4'b0000}};



  assign Discrete_Time_Integrator3_u_dtc = Discrete_Time_Integrator3_u_gain;



  assign Discrete_Time_Integrator3_ic = 46'sh000000000000;



  always_ff @(posedge clk or posedge reset)
    begin : intdelay_11_process
      if (reset == 1'b1) begin
        Discrete_Time_Integrator3_add_in <= 46'sh000000000000;
      end
      else begin
        if (enb) begin
          Discrete_Time_Integrator3_add_in <= Discrete_Time_Integrator3_x_reg;
        end
      end
    end



  assign Discrete_Time_Integrator3_u_add = Discrete_Time_Integrator3_add_in + Discrete_Time_Integrator3_u_dtc;



  assign Discrete_Time_Integrator3_x_reg = (Compare_To_Constant_out1_rEdge_3 == 1'b0 ? Discrete_Time_Integrator3_u_add :
              Discrete_Time_Integrator3_ic);



  always_ff @(posedge clk or posedge reset)
    begin : Delay12_process
      if (reset == 1'b1) begin
        Delay12_out1 <= 46'sh000000000000;
      end
      else begin
        if (enb) begin
          Delay12_out1 <= Discrete_Time_Integrator3_x_reg;
        end
      end
    end



  assign Data_Type_Conversion3_out1 = Delay12_out1[45:24];



  assign Product7_mul_temp = Data_Type_Conversion3_out1 * Data_Type_Conversion3_out1;
  assign Product7_out1 = {{4{Product7_mul_temp[43]}}, Product7_mul_temp[43:5]};



  always_ff @(posedge clk or posedge reset)
    begin : Delay16_process
      if (reset == 1'b1) begin
        Delay16_out1 <= 43'sh00000000000;
      end
      else begin
        if (enb) begin
          Delay16_out1 <= Product7_out1;
        end
      end
    end



  assign Sum1_add_cast = {Delay15_out1[42], Delay15_out1};
  assign Sum1_add_cast_1 = {Delay16_out1[42], Delay16_out1};
  assign Sum1_out1 = Sum1_add_cast + Sum1_add_cast_1;



  always_ff @(posedge clk or posedge reset)
    begin : Delay18_process
      if (reset == 1'b1) begin
        Delay18_out1 <= 44'sh00000000000;
      end
      else begin
        if (enb) begin
          Delay18_out1 <= Sum1_out1;
        end
      end
    end



  assign Sum2_sub_temp = Delay17_out1 - Delay18_out1;
  assign Sum2_out1 = {Sum2_sub_temp[43], Sum2_sub_temp};



  always_ff @(posedge clk or posedge reset)
    begin : Delay19_process
      if (reset == 1'b1) begin
        Delay19_out1 <= 45'sh000000000000;
      end
      else begin
        if (enb) begin
          Delay19_out1 <= Sum2_out1;
        end
      end
    end



  assign Constant_out1 = 44'sh00000000000;



  assign Relational_Operator_cast = {Constant_out1[43], Constant_out1};
  assign Relational_Operator_out1 = Delay19_out1 > Relational_Operator_cast;



  Sample_and_Hold u_Sample_and_Hold (.clk(clk),
                                     .reset(reset),
                                     .enb(clk_enable),
                                     .In(Relational_Operator_out1),
                                     .Trigger(Compare_To_Constant_out1),
                                     .alpha(Sample_and_Hold_out1)
                                     );

  assign demodulated_signal = Sample_and_Hold_out1;

  assign ce_out = clk_enable;

endmodule  // FSK_DEMODULATOR_HARDWARE_MODEL

