// -------------------------------------------------------------
// 
// File Name: C:\Users\pc\Documents\MATLAB\MY_FSK\HDL_DEMODULATOR\hdlsrc\FSK_DEMODULATOR_HARDWARE_MODEL\HARDWARE_FRIENDLY_FSK\FSK_DEMODULATOR_HARDWARE_MODEL_pkg.sv
// Created: 2026-04-28 11:08:04
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------



package FSK_DEMODULATOR_HARDWARE_MODEL_pkg;
  typedef  logic signed [15:0] vector_of_signed_logic_16;

  typedef  logic signed [17:0] vector_of_signed_logic_18;
endpackage: FSK_DEMODULATOR_HARDWARE_MODEL_pkg

