%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Auto generated cosimulation 'tclstart' script 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Source Model         : HARDWARE_FRIENDLY_FSK
%  Generated Model      : gm_HARDWARE_FRIENDLY_FSK
%  Cosimulation Model   : gm_HARDWARE_FRIENDLY_FSK_mq
%
%  Source DUT           : gm_HARDWARE_FRIENDLY_FSK_mq/FSK_DEMODULATOR_HARDWARE_MODEL
%  Cosimulation DUT     : gm_HARDWARE_FRIENDLY_FSK_mq/FSK_DEMODULATOR_HARDWARE_MODEL_mq
%
%  File Location        : C:\Users\pc\Documents\MATLAB\MY_FSK\HDL_DEMODULATOR\hdlsrc\FSK_DEMODULATOR_HARDWARE_MODEL\HARDWARE_FRIENDLY_FSK\gm_HARDWARE_FRIENDLY_FSK_mq_tcl.m
%  Created              : 2026-04-28 11:17:00
%
%  Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  ClockName           : clk
%  ResetName           : reset 
%  ClockEnableName     : clk_enable
%
%  ClockLowTime        : 5ns
%  ClockHighTime       : 5ns
%  ClockPeriod         : 10ns
%
%  ResetLength         : 20ns
%  ClockEnableDelay    : 10ns
%  HoldTime            : 2ns
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  ModelBaseSampleTime   : 1e-08
%  DutBaseSampleTime     : 1e-08
%  OverClockFactor     : 1
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Mapping of DutBaseSampleTime to ClockPeriod
%
%  N = (ClockPeriod / DutBaseSampleTime) * OverClockFactor
%  1 sec in Simulink corresponds to 1e+09ns in the HDL Simulator(N = 1e+09)
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  ResetHighAt          : (ClockLowTime + ResetLength + HoldTime)
%  ResetRiseEdge        : 27ns
%  ResetType            : async
%  ResetAssertedLevel   : 1
%
%  ClockEnableHighAt    : (ClockLowTime + ResetLength + ClockEnableDelay + HoldTime)
%  ClockEnableRiseEdge  : 37ns
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

function tclCmds = gm_HARDWARE_FRIENDLY_FSK_mq_tcl
tclCmds = {
    'do FSK_DEMODULATOR_HARDWARE_MODEL_compile.do',...% Compile the generated code
    'vsimulink -voptargs=+acc  work.FSK_DEMODULATOR_HARDWARE_MODEL',...% Initiate cosimulation
    'add wave  /FSK_DEMODULATOR_HARDWARE_MODEL/clk',...% Add wave commands for chip input signals
    'add wave  /FSK_DEMODULATOR_HARDWARE_MODEL/reset',...
    'add wave  /FSK_DEMODULATOR_HARDWARE_MODEL/clk_enable',...
    'add wave  /FSK_DEMODULATOR_HARDWARE_MODEL/modulated_signal',...
    'add wave  /FSK_DEMODULATOR_HARDWARE_MODEL/ce_out',...% Add wave commands for chip output signals
    'add wave  /FSK_DEMODULATOR_HARDWARE_MODEL/demodulated_signal',...
    'set UserTimeUnit ns',...% Set simulation time unit
    'puts ""',...
    'puts "Ready for cosimulation..."',...
};
end