// -------------------------------------------------------------
// 
// File Name: C:\Users\pc\Documents\MATLAB\MY_FSK\HDL_DEMODULATOR\hdlsrc\FSK_DEMODULATOR_HARDWARE_MODEL\HARDWARE_FRIENDLY_FSK\NCO.sv
// Created: 2026-04-28 11:08:04
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


import FSK_DEMODULATOR_HARDWARE_MODEL_pkg::* ;

// -------------------------------------------------------------
// 
// Module: NCO
// Source Path: HARDWARE_FRIENDLY_FSK/FSK_DEMODULATOR_HARDWARE_MODEL/NCO
// Hierarchy Level: 1
// Model version: 1.17
// 
// NCO
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module NCO
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic validIn,
             output logic signed [15:0] sine  /* sfix16_En15 */,
             output logic signed [15:0] cosine  /* sfix16_En15 */);


  logic [4:0] outsel_reg_reg;  /* ufix1 [5] */
  logic outsel;
  logic signed [15:0] outzero;  /* sfix16_En15 */
  logic signed [27:0] const0;  /* sfix28 */
  logic signed [27:0] pInc;  /* sfix28 */
  logic signed [27:0] validPInc;  /* sfix28 */
  logic signed [27:0] accphase_reg;  /* sfix28 */
  logic signed [27:0] addpInc;  /* sfix28 */
  logic signed [27:0] pOffset;  /* sfix28 */
  logic signed [27:0] accoffset;  /* sfix28 */
  logic signed [27:0] accoffsete_reg;  /* sfix28 */
  logic [14:0] dither;  /* ufix15 */
  logic signed [27:0] casteddither;  /* sfix28 */
  logic signed [27:0] dither_reg;  /* sfix28 */
  logic signed [27:0] accumulator;  /* sfix28 */
  logic [12:0] accQuantized;  /* ufix13_E15 */
  logic signed [15:0] outsine;  /* sfix16_En15 */
  logic signed [15:0] outcos;  /* sfix16_En15 */
  logic signed [15:0] validsine;  /* sfix16_En15 */
  logic signed [15:0] sine_1;  /* sfix16_En15 */
  logic signed [15:0] validcos;  /* sfix16_En15 */
  logic signed [15:0] cosine_1;  /* sfix16_En15 */


  always_ff @(posedge clk or posedge reset)
    begin : outsel_reg_process
      if (reset == 1'b1) begin
        outsel_reg_reg <= '{5{1'b0}};
      end
      else begin
        if (enb) begin
          outsel_reg_reg[0] <= validIn;
          outsel_reg_reg[32'sd4:32'sd1] <= outsel_reg_reg[32'sd3:32'sd0];
        end
      end
    end

  assign outsel = outsel_reg_reg[4];



  assign outzero = 16'sb0000000000000000;



  // Constant Zero
  assign const0 = 28'sb0000000000000000000000000000;



  assign pInc = 28'sb0000000000000111110111010100;



  assign validPInc = (validIn == 1'b0 ? const0 :
              pInc);



  // Add phase increment
  assign addpInc = accphase_reg + validPInc;



  // Phase increment accumulator register
  always_ff @(posedge clk or posedge reset)
    begin : AccPhaseRegister_process
      if (reset == 1'b1) begin
        accphase_reg <= 28'sb0000000000000000000000000000;
      end
      else begin
        if (enb) begin
          accphase_reg <= addpInc;
        end
      end
    end



  assign pOffset = 28'sb0000000000000000000000000000;



  // Add phase offset
  assign accoffset = accphase_reg + pOffset;



  // Phase offset accumulator register
  always_ff @(posedge clk or posedge reset)
    begin : AccOffsetRegister_process
      if (reset == 1'b1) begin
        accoffsete_reg <= 28'sb0000000000000000000000000000;
      end
      else begin
        if (enb) begin
          accoffsete_reg <= accoffset;
        end
      end
    end



  DitherGen u_dither_inst (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .validIn(validIn),
                           .dither(dither)  /* ufix15 */
                           );

  assign casteddither = {13'b0, dither};



  // Dither input register
  always_ff @(posedge clk or posedge reset)
    begin : DitherRegister_process
      if (reset == 1'b1) begin
        dither_reg <= 28'sb0000000000000000000000000000;
      end
      else begin
        if (enb) begin
          dither_reg <= casteddither;
        end
      end
    end



  // Add dither
  assign accumulator = accoffsete_reg + dither_reg;



  // Phase quantization
  assign accQuantized = accumulator[27:15];



  WaveformGen u_Wave_inst (.clk(clk),
                           .reset(reset),
                           .enb(enb),
                           .phaseIdx(accQuantized),  /* ufix13_E15 */
                           .sine(outsine),  /* sfix16_En15 */
                           .cosine(outcos)  /* sfix16_En15 */
                           );

  assign validsine = (outsel == 1'b0 ? outzero :
              outsine);



  // Output sine register
  always_ff @(posedge clk or posedge reset)
    begin : OutSineRegister_process
      if (reset == 1'b1) begin
        sine_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          sine_1 <= validsine;
        end
      end
    end



  assign validcos = (outsel == 1'b0 ? outzero :
              outcos);



  // Output cosine register
  always_ff @(posedge clk or posedge reset)
    begin : OutCosineRegister_process
      if (reset == 1'b1) begin
        cosine_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          cosine_1 <= validcos;
        end
      end
    end



  assign sine = sine_1;

  assign cosine = cosine_1;

endmodule  // NCO

