// -------------------------------------------------------------
// 
// File Name: C:\Users\pc\Documents\MATLAB\MY_FSK\HDL_DEMODULATOR\hdlsrc\FSK_DEMODULATOR_HARDWARE_MODEL\HARDWARE_FRIENDLY_FSK\Sample_and_Hold.sv
// Created: 2026-04-28 11:08:04
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Sample_and_Hold
// Source Path: HARDWARE_FRIENDLY_FSK/FSK_DEMODULATOR_HARDWARE_MODEL/Sample and Hold
// Hierarchy Level: 1
// Model version: 1.17
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Sample_and_Hold
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic In,
             input logic Trigger,
             output logic alpha);


  logic enb_gated;
  logic Trigger_delayed;
  logic Trigger_emulated;
  logic In_bypass;
  logic In_last_value;


  always @(posedge clk or posedge reset)
    begin : Trigger_delay
      if (reset) begin
        Trigger_delayed <= 1'b1;
      end
      else begin
        if (enb) begin
          Trigger_delayed <= Trigger;
        end
      end
    end

  assign Trigger_emulated = !Trigger_delayed && Trigger;

  assign enb_gated = Trigger_emulated && enb;

  always_ff @(posedge clk or posedge reset)
    begin : alpha_bypass_process
      if (reset == 1'b1) begin
        In_last_value <= 1'b0;
      end
      else begin
        if (enb_gated) begin
          In_last_value <= In_bypass;
        end
      end
    end



  assign In_bypass = (Trigger_emulated == 1'b0 ? In_last_value :
              In);



  assign alpha = In_bypass;

endmodule  // Sample_and_Hold

