// -------------------------------------------------------------
// 
// File Name: C:\Users\pc\Documents\MATLAB\MY_FSK\HDL_DEMODULATOR\hdlsrc\FSK_DEMODULATOR_HARDWARE_MODEL\HARDWARE_FRIENDLY_FSK\WaveformGen_block.sv
// Created: 2026-04-28 11:08:04
// 
// Generated by MATLAB 24.1, HDL Coder 24.1, and Simulink 24.1
// 
// -------------------------------------------------------------


import FSK_DEMODULATOR_HARDWARE_MODEL_pkg::* ;

// -------------------------------------------------------------
// 
// Module: WaveformGen_block
// Source Path: HARDWARE_FRIENDLY_FSK/FSK_DEMODULATOR_HARDWARE_MODEL/NCO1/WaveformGen
// Hierarchy Level: 2
// Model version: 1.17
// 
// Wave form Generation Component
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module WaveformGen_block
          (  input logic clk,
             input logic reset,
             input logic enb,
             input logic [12:0] phaseIdx  /* ufix13_E15 */,
             output logic signed [17:0] sine  /* sfix18_En17 */,
             output logic signed [17:0] cosine  /* sfix18_En17 */);


  logic [12:0] phaseIdxReg;  /* ufix13_E15 */
  logic msb1;  /* ufix1 */
  logic [2:0] sineSignSelRegComp_reg;  /* ufix1 [3] */
  logic sineSignSelReg;  /* ufix1 */
  logic [10:0] lutaddr1;  /* ufix11 */
  logic sin45Sel;  /* ufix1 */
  logic [2:0] sin45SelRegComp_reg;  /* ufix1 [3] */
  logic sin45SelReg;  /* ufix1 */
  logic msb2;  /* ufix1 */
  logic msb3;  /* ufix1 */
  logic lutSel;  /* ufix1 */
  logic [2:0] lutSelRegComp_reg;  /* ufix1 [3] */
  logic lutSelReg;  /* ufix1 */
  logic [11:0] lutaddrmax;  /* ufix12 */
  logic [12:0] subtractor_sub_temp;  /* ufix13 */
  logic [12:0] subtractor_1;  /* ufix13 */
  logic [12:0] subtractor_2;  /* ufix13 */
  logic [10:0] lutaddr2;  /* ufix11 */
  logic [10:0] lutaddr;  /* ufix11 */
  logic [9:0] lutaddrO;  /* ufix10 */
  logic signed [17:0] lutoutsin;  /* sfix18_En17 */
  logic signed [17:0] lutoutcos;  /* sfix18_En17 */
  logic signed [17:0] lutselsin;  /* sfix18_En17 */
  logic signed [17:0] octantVal;  /* sfix18_En17 */
  logic signed [17:0] fullsinmag;  /* sfix18_En17 */
  logic signed [18:0] uminus_cast;  /* sfix19_En17 */
  logic signed [18:0] uminus_cast_1;  /* sfix19_En17 */
  logic signed [17:0] inverseSin;  /* sfix18_En17 */
  logic signSel;  /* ufix1 */
  logic [2:0] signSelRegComp_reg;  /* ufix1 [3] */
  logic signSelReg;  /* ufix1 */
  logic signed [17:0] lutselcos;  /* sfix18_En17 */
  logic signed [17:0] fullcosmag;  /* sfix18_En17 */
  logic signed [18:0] uminus_cast_2;  /* sfix19_En17 */
  logic signed [18:0] uminus_cast_3;  /* sfix19_En17 */
  logic signed [17:0] inverseCos;  /* sfix18_En17 */


  always_ff @(posedge clk or posedge reset)
    begin : phaseIdxRegister_process
      if (reset == 1'b1) begin
        phaseIdxReg <= 13'b0000000000000;
      end
      else begin
        if (enb) begin
          phaseIdxReg <= phaseIdx;
        end
      end
    end



  // Sine sign selection signal
  assign msb1 = phaseIdxReg[12];



  always_ff @(posedge clk or posedge reset)
    begin : sineSignSelRegComp_process
      if (reset == 1'b1) begin
        sineSignSelRegComp_reg <= '{3{1'b0}};
      end
      else begin
        if (enb) begin
          sineSignSelRegComp_reg[0] <= msb1;
          sineSignSelRegComp_reg[32'sd2:32'sd1] <= sineSignSelRegComp_reg[32'sd1:32'sd0];
        end
      end
    end

  assign sineSignSelReg = sineSignSelRegComp_reg[2];



  assign lutaddr1 = phaseIdxReg[10:0];



  // 45 degree address
  assign sin45Sel = lutaddr1 == 11'b10000000000;



  always_ff @(posedge clk or posedge reset)
    begin : sin45SelRegComp_process
      if (reset == 1'b1) begin
        sin45SelRegComp_reg <= '{3{1'b0}};
      end
      else begin
        if (enb) begin
          sin45SelRegComp_reg[0] <= sin45Sel;
          sin45SelRegComp_reg[32'sd2:32'sd1] <= sin45SelRegComp_reg[32'sd1:32'sd0];
        end
      end
    end

  assign sin45SelReg = sin45SelRegComp_reg[2];



  assign msb2 = phaseIdxReg[11];



  assign msb3 = phaseIdxReg[10];



  // LUT selection signal
  assign lutSel = msb2 ^ msb3;



  always_ff @(posedge clk or posedge reset)
    begin : lutSelRegComp_process
      if (reset == 1'b1) begin
        lutSelRegComp_reg <= '{3{1'b0}};
      end
      else begin
        if (enb) begin
          lutSelRegComp_reg[0] <= lutSel;
          lutSelRegComp_reg[32'sd2:32'sd1] <= lutSelRegComp_reg[32'sd1:32'sd0];
        end
      end
    end

  assign lutSelReg = lutSelRegComp_reg[2];



  // Map LUT address in correct phase
  assign lutaddrmax = 12'b100000000000;



  assign subtractor_1 = {1'b0, lutaddrmax};
  assign subtractor_2 = {2'b0, lutaddr1};
  assign subtractor_sub_temp = subtractor_1 - subtractor_2;
  assign lutaddr2 = subtractor_sub_temp[10:0];



  assign lutaddr = (msb3 == 1'b0 ? lutaddr1 :
              lutaddr2);



  assign lutaddrO = lutaddr[9:0];



  SinLookUpTableGen_block u_Sin_Wave_inst (.clk(clk),
                                           .reset(reset),
                                           .enb(enb),
                                           .lutaddr(lutaddrO),  /* ufix10 */
                                           .lutSine(lutoutsin)  /* sfix18_En17 */
                                           );

  CosLookUpTableGen_block u_Cos_Wave_inst (.clk(clk),
                                           .reset(reset),
                                           .enb(enb),
                                           .lutaddr(lutaddrO),  /* ufix10 */
                                           .lutCosine(lutoutcos)  /* sfix18_En17 */
                                           );

  // Select sine output LUT
  assign lutselsin = (lutSelReg == 1'b0 ? lutoutsin :
              lutoutcos);



  assign octantVal = 18'sb010110101000001010;



  // Assign sine pi/4 value
  assign fullsinmag = (sin45SelReg == 1'b0 ? lutselsin :
              octantVal);



  assign uminus_cast = {fullsinmag[17], fullsinmag};
  assign uminus_cast_1 =  - (uminus_cast);
  assign inverseSin = uminus_cast_1[17:0];



  // Select sign of sine output
  assign sine = (sineSignSelReg == 1'b0 ? fullsinmag :
              inverseSin);



  // Cosine sign selection signal
  assign signSel = msb1 ^ msb2;



  always_ff @(posedge clk or posedge reset)
    begin : signSelRegComp_process
      if (reset == 1'b1) begin
        signSelRegComp_reg <= '{3{1'b0}};
      end
      else begin
        if (enb) begin
          signSelRegComp_reg[0] <= signSel;
          signSelRegComp_reg[32'sd2:32'sd1] <= signSelRegComp_reg[32'sd1:32'sd0];
        end
      end
    end

  assign signSelReg = signSelRegComp_reg[2];



  // Select cosine output LUT
  assign lutselcos = (lutSelReg == 1'b0 ? lutoutcos :
              lutoutsin);



  // Assign cosine pi/4 value
  assign fullcosmag = (sin45SelReg == 1'b0 ? lutselcos :
              octantVal);



  assign uminus_cast_2 = {fullcosmag[17], fullcosmag};
  assign uminus_cast_3 =  - (uminus_cast_2);
  assign inverseCos = uminus_cast_3[17:0];



  // Select sign of cosine ouptput
  assign cosine = (signSelReg == 1'b0 ? fullcosmag :
              inverseCos);



endmodule  // WaveformGen_block

